baseURL: https://mink-teeraseranee.netlify.app/
languageCode: en-us
title: Portfolio website for Mink Teeraseranee
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: This is a portfolio filled with models that I have toiled over for hours. Hope you find it interesting
      #A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      #AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Mink
  blog: {}
  contact:
    address:
      - city: London, NW1 4SA
        country: United Kingdom
        street: Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: minkt.mba2024@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7765-735339 
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Mink Teeraseranee
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
 #     - icon: fa-twitter
 #       label: Twitter
  #      url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/mink.teeraseranee
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/minkvarachya
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/mink
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/mink-teeraseranee
  image: ''
  name: Your name
  navigation:
    button1:
      - name: My CV
        url: blogs/CV
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: headshot.jpg
        subtitle: CV
        title: Profile
        url: blogs/CV
      - image: khao.jpg
        subtitle: Hobbies
        title: Interests
        url: blogs/interests
      - image: volunteer.jpg
        subtitle: Volunteer
        title: Mentoring
        url: blogs/Volunteer
      - image: lbs.jpg
        subtitle: R-programing
        title: Data Science Homework
        url: blogs/homework2
      #- image: pic05.jpg
      #  subtitle: Ipsum Dolor Sit Amet
      #  title: Consequat
      #  url: blogs/ipsum
      # - image: pic06.jpg
      #  subtitle: Feugiat Amet Tempus
      #  title: Etiam
      #  url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: This is my portfolio filled with models that I have toiled over for hours. Hope you find it interesting
    title: My Projects
    url: blogs
